# Generated by Django 5.1.3 on 2024-12-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('gig', 'Gig'), ('collaboration', 'Collaboration')], default='gig', max_length=20),
        ),
    ]
