# Generated by Django 5.1.3 on 2024-12-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, default='event_images/default_image.png', null=True, upload_to='event_images/'),
        ),
    ]
