# Generated by Django 5.1.3 on 2024-12-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, default='event_images/default-image.png', null=True, upload_to='event_images/'),
        ),
    ]
