# Generated by Django 5.1.3 on 2024-12-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
